spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_project?serverTimeZone=Asia/Seoul&CharacterEncoding=UTF-8
    username: root
    password: gt22073518
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 487263303071-krt3a9aao9n9hkv7vbep57gc1ggom36c.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: email


jwt:
  issuer: gmltjd@naver.com
  secret_key: db_projectdb_projectdb_projectdb_projectdb_projectdb_project

